### ISSUE TITLE
ToDo list for next version

### ISSUE THREAD

**Issue by rebelucho** [rebelucho/online-scores#6]
- [x] Необходимо добавить сессии посетителей для запоминания последних реквизитов поиска и настроек сайта.
- [ ] определение часового пояса, автоматическое изменение часового пояса для правильной выгрузки списка игр за дату, возможность установки часового пояса посетителем
- [ ] формирование короткой ссылки на игры для публикации в мессенджерах
- [ ] раздел администрирования сайта для изменения оформления и наполнения дополнительных страниц
